name: ⛅ CF

on:
  schedule:
    # At 7:53 on 3rd, 10th, 18th, 26th of every month
    - cron: '53 7 3,10,18,26 * *'
  
  push:
    # Trigger on push to main branch and tags matching v*
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/cf.yml"
      - ".env.example"
      - ".eslintrc.cjs"
      - ".prettierignore"
      - "fly.toml"
      - "README.md"
      - "node.Dockerfile"
      - "deno.Dockerfile"
      - "import_map.json"
      - ".vscode/*"
      - ".husky/*"
      - ".prettierrc.json"
      - "LICENSE"
      - "run"

  repository_dispatch:

  workflow_dispatch:
    inputs:
      environment:
        description: 'wrangler env to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - one
      commit:
        description: 'git tip commit to deploy'
        default: 'main'
        required: true

env:
  GIT_REF: ${{ github.event.inputs.commit || github.ref }}
  WRANGLER_VER: '3.56.0'
  WORKERS_ENV: ''

jobs:
  deploy:
    name: 🚀 Deploy worker
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}
          fetch-depth: 0

      - name: 🛸 Env?
        if: github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'one'
        run: |
          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
        shell: bash
        env:
          WENV: ${{ github.event.inputs.environment }}
          COMMIT_SHA: ${{ github.sha }}

      - name: 🎱 Tag?
        if: github.ref_type == 'tag'
        run: |
          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
        shell: bash
        env:
          WENV: 'prod'
          COMMIT_SHA: ${{ github.sha }}

      - name: 🌽 Cron?
        if: github.event.schedule == '53 7 3,10,18,26 * *'
        run: |
          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
        shell: bash
        env:
          WENV: 'prod'
          COMMIT_SHA: ${{ github.sha }}

      # npm (and node16) are installed by wrangler-action in a pre-job setup
      - name: 🏗 Get dependencies
        run: npm i

      - name: 📚 Wrangler publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ env.WORKERS_ENV }}
          wranglerVersion: ${{ env.WRANGLER_VER }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GIT_COMMIT_ID: ${{ env.COMMIT_SHA }}

      - name: 🎤 Notice
        run: |
          echo "::notice::Deployed to ${WORKERS_ENV} / ${GIT_REF} @ ${COMMIT_SHA}"
